image: registry.access.redhat.com/ubi9/buildah

variables:
  CI_REGISTRY: quay.io
  CI_REGISTRY_IMAGE: $CI_REGISTRY/redhat-saia/quarkus-routing-service

stages:
  - build-jar
  - build-image

cache:
  paths:
    - target/

build-jar:
  stage: build-jar
  image: registry.access.redhat.com/ubi8/openjdk-21:latest
  script:
  # Need to download the model from Huggingface to big to check in to our gitlab
    - curl -L https://huggingface.co/nomic-ai/nomic-embed-text-v1/resolve/main/onnx/model_quantized.onnx?download=true --output curl -L https://huggingface.co/nomic-ai/nomic-embed-text-v1/resolve/main/onnx/model_quantized.onnx?download=true --output src/main/resources/embeddings/nomic/model.onnx
    - ls -al src/main/resources/embeddings/nomic/
    - ls -al .
    - mvn clean package
    - ls -alh target

build-image:
  stage: build-image
  script:
    - echo $CI_REGISTRY_PASSWORD | buildah login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - buildah bud -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --ulimit nofile=4096:4096 .
    - buildah push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - buildah tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG $CI_REGISTRY_IMAGE:latest
    - buildah push $CI_REGISTRY_IMAGE:latest
    
  tags:
    - aws # Run on the AWS runner (Openshift runner has issues building images)
  rules:
    - if: '$CI_COMMIT_TAG'
      when: always
    - when: never

